### ISSUE TITLE
Is this redundant? If not, I cannot tell which view it is relate to.

### ISSUE THREAD

**Issue by coiller** [anggutierrez/foodstack#23]
https://github.com/anggutierrez/foodstack/blob/3a489214c87cbd40cec559ab7d74a6b0dc2d61e4/foodstack/ViewController.m#L15

**Comment by anggutierrez** [comment]
Originally left this view controller in as all my other classes that were a subclass of "UIViewController" would crash whenever I deleted "ViewController.m" and "ViewController.h"

It seemed to not have broken my program this time, so I have now deleted this file
