### ISSUE TITLE
Why not use "."

### ISSUE THREAD

**Issue by coiller** [anggutierrez/foodstack#26]
https://github.com/anggutierrez/foodstack/blob/3a489214c87cbd40cec559ab7d74a6b0dc2d61e4/foodstack/Views/EntryCell.m#L24
e.g.
```
self.entryTitle.text = entry.entryTitle;

**Comment by anggutierrez** [comment]
I was unaware you could access data from Parse this way, I was mainly following the directions from the previous Codepath course.

I will refrain from accessing data the Codepath way in the future, and instead use the way you taught me instead.

Completed
