### ISSUE TITLE
You are not formating here. Cast type is enough, right?

### ISSUE THREAD

**Issue by coiller** [anggutierrez/foodstack#27]
https://github.com/anggutierrez/foodstack/blob/3a489214c87cbd40cec559ab7d74a6b0dc2d61e4/foodstack/Views/EntryCell.m#L27
e.g.
```
NSString *calories = [entry.calCount stringValue]; 
```
If you do not know how to do that, do some research is always your first step.

**Comment by anggutierrez** [comment]
stringWithFormat was the only way I knew how to add variables into a string. After looking at your suggestion, I see how it could be redundant to use a string formatter for only one variable.

I was unaware there was a built-in method to cast values to strings other than the usual (NSString *)

I have changed that line and will look forward to seeing different ways to cast variables in the future
