### ISSUE TITLE
Is this method necessary?

### ISSUE THREAD

**Issue by coiller** [anggutierrez/foodstack#31]
https://github.com/anggutierrez/foodstack/blob/3a489214c87cbd40cec559ab7d74a6b0dc2d61e4/foodstack/View%20Controllers/Compose%20Views/ComposeEntryViewController.m#L26
- first, you can return ``` !self.composeTitleField.hasText && !self.composeCalField.hasText && !self.composeDescField.hasText``` directly
- looks it is not reused and not large enough to be extracted out

**Comment by anggutierrez** [comment]
Originally, this was code you suggested I refactor into the "isEmpty" function about 1-2 weeks ago. 

The code used to instantiate an alert for when the different fields were empty. When I started writing this code I didn't want to deal with error handling just yet, so I cut out that part of the code and left it as a smaller function.

The function is supposed to have more code, like this:

    - (bool) _isEmpty {
	if (self.composeTitleField.hasText && self.composeCalField.hasText && self.composeDescField.hasText) {
		return NO;
	}
	UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"Missing Title, Calories, or Description!" message:@"Fill in the required fields." preferredStyle:(UIAlertControllerStyleAlert)];
	
	UIAlertAction *okAction = [UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {}];
	
	[alert addAction:okAction];
	
	[self presentViewController:alert animated:YES completion:^{
	}];
	
	return YES;
    }

I have changed the code to reflect the original vision for this function. Please let me know if having its own function is still not justified as it is only used once in the function
